// Lightweight fetch helpers for endpoints not generated by orval (users, leaderboard).
// Mirrors the base path used by the generated client.

const BASE = "/api";

export type AppUser = {
  id: number;
  name: string;
  avatarEmoji: string | null;
  createdAt: string;
  lastSeenAt: string;
};

export type LeaderboardEntry = {
  id?: number;
  userId: number;
  userName: string | null;
  avatarEmoji: string | null;
  gameType: string;
  score: number;
  accuracy: number;
  difficulty: number;
  achievedAt: string;
};

export type ProfileBundle = {
  user: AppUser;
  profile: {
    totalStars: number;
    totalGamesPlayed: number;
  } | null;
  stats: {
    totalGames: number;
    totalScore: number;
    avgAccuracy: number;
  };
};

export async function upsertUser(name: string, avatarEmoji?: string): Promise<AppUser> {
  const res = await fetch(`${BASE}/users/upsert`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name, avatarEmoji }),
  });
  if (!res.ok) throw new Error(`upsertUser failed: ${res.status}`);
  const data = await res.json();
  return data.user as AppUser;
}

export async function getProfile(userId: number): Promise<ProfileBundle> {
  const res = await fetch(`${BASE}/users/${userId}/profile`);
  if (!res.ok) throw new Error(`getProfile failed: ${res.status}`);
  return res.json();
}

export async function getLeaderboard(opts?: {
  gameType?: string;
  limit?: number;
}): Promise<{ entries: LeaderboardEntry[] }> {
  const params = new URLSearchParams();
  if (opts?.gameType) params.set("gameType", opts.gameType);
  if (opts?.limit) params.set("limit", String(opts.limit));
  const qs = params.toString();
  const res = await fetch(`${BASE}/leaderboard${qs ? `?${qs}` : ""}`);
  if (!res.ok) throw new Error(`getLeaderboard failed: ${res.status}`);
  return res.json();
}

export async function getTopByGame(): Promise<{ games: Record<string, LeaderboardEntry[]> }> {
  const res = await fetch(`${BASE}/leaderboard/top-by-game`);
  if (!res.ok) throw new Error(`getTopByGame failed: ${res.status}`);
  return res.json();
}

// Local helpers
export function getCurrentUserId(): number | null {
  const raw = localStorage.getItem("brightways_user_id");
  if (!raw) return null;
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
}

export function getCurrentUserName(): string | null {
  return localStorage.getItem("brightways_name");
}

export function setCurrentUser(user: AppUser) {
  localStorage.setItem("brightways_user_id", String(user.id));
  localStorage.setItem("brightways_name", user.name);
  if (user.avatarEmoji) localStorage.setItem("brightways_avatar", user.avatarEmoji);
}
